from datetime import datetime
from typing import Any
import uuid
from pydantic import BaseModel, Field


class DesktopTokenRequest(BaseModel):
    grant_type: str = Field(..., description="authorization_code or refresh_token")
    client_id: str = Field("revitapp-desktop", description="Public client ID")
    code: str | None = Field(None, description="Authorization code for authorization_code grant")
    code_verifier: str | None = Field(None, description="PKCE code verifier for authorization_code grant")
    redirect_uri: str | None = Field(None, description="Redirect URI matching authorization request")
    refresh_token: str | None = Field(None, description="Refresh token for refresh_token grant")


class DesktopTokenResponse(BaseModel):
    access_token: str
    token_type: str = "Bearer"
    expires_in: int = 900
    refresh_token: str | None = None
    scope: str = "all"


class DeviceActivateRequest(BaseModel):
    productCode: str = Field("revitapp", description="Product code e.g. revitapp")
    installationId: str = Field(..., description="UUID generated by Revit Add-in upon install")
    machineFingerprint: str = Field(..., description="SHA-256 hash of hardware signals")
    displayName: str = Field("DESKTOP-DEVICE", description="Computer name")
    platform: str = Field("windows", description="OS platform")
    revitVersion: str = Field("2025", description="Revit version")
    appVersion: str = Field("1.0.0", description="Add-in app version")


class DeviceHeartbeatRequest(BaseModel):
    deviceId: str | None = None
    installationId: str | None = None
    machineFingerprint: str | None = None


class LicenseCheckRequest(BaseModel):
    product_code: str = Field("revitapp", description="Product code e.g. revitapp")
    hardware_fingerprint: str = Field(..., description="SHA-256 hash of hardware signals")
    device_name: str | None = Field(None, description="Computer name")
    revit_version: str | None = Field(None, description="Revit version e.g. 2025")
    installation_id: str | None = Field(None, description="Client installation UUID")
    device_id: str | None = Field(None, description="Existing device activation UUID if any")


class EntitlementResponse(BaseModel):
    allowed: bool
    product: str | None = None
    licenseId: str | None = None
    deviceId: str | None = None
    plan: str | None = None
    isTrial: bool = False
    expiresAt: str | None = None
    features: list[str] = []
    serverTime: str
    refreshAfterSeconds: int = 300
    error: str | None = None
    message: str | None = None
