import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, Check } from 'lucide-react';

const features = [
  { id:'batch-rename', title:'Đổi tên hàng loạt', category:'Quản lý dự án', description:'Đổi tên View, Sheet và Family theo quy tắc tiền tố, hậu tố hoặc số thứ tự. Xem trước toàn bộ thay đổi trước khi áp dụng.', image:'/assets/product/batch-rename.webp', bullets:['Xem trước Trước/Sau','Lọc và chọn nhiều hạng mục','Hoàn tác an toàn'] },
  { id:'auto-dimension', title:'Ghi kích thước tự động', category:'Khai triển bản vẽ', description:'Tạo chuỗi kích thước cho tường, cột, dầm, sàn và cửa theo tiêu chuẩn của dự án chỉ trong một lần chạy.', image:'/assets/product/auto-dimension.webp', bullets:['Thiết lập theo tiêu chuẩn','Nhận diện cấu kiện thông minh','Cập nhật đồng bộ'] },
  { id:'parameter-manager', title:'Quản lý tham số', category:'Quản lý dữ liệu', description:'Kiểm tra, tính toán và đồng bộ tham số giữa nhiều nhóm đối tượng mà không cần viết Dynamo.', image:'/assets/product/parameter-manager.webp', bullets:['Bảng trạng thái trực quan','Áp dụng quy tắc hàng loạt','Xuất dữ liệu Excel'] },
  { id:'sheet-publisher', title:'Xuất bản bản vẽ', category:'Hồ sơ', description:'Chọn hàng loạt Sheet, lưu cấu hình và theo dõi hàng đợi xuất bản PDF hoặc DWG trong một màn hình.', image:'/assets/product/sheet-publisher.webp', bullets:['Chọn Sheet bằng bộ lọc','Lưu cấu hình xuất bản','Theo dõi từng trạng thái'] },
  { id:'batch-exporter', title:'Xuất file hàng loạt', category:'Trao đổi dữ liệu', description:'Xuất PDF, DWG và IFC theo quy tắc đặt tên thống nhất, với tiến trình và kết quả rõ ràng.', image:'/assets/product/batch-exporter.webp', bullets:['PDF, DWG và IFC','Đặt tên file tự động','Báo lỗi theo từng file'] },
];
export default function FeaturesPage() {
  return <div className="pb-16"><header className="page-shell pt-14 pb-12 max-w-2xl"><h1 className="text-4xl sm:text-5xl font-extrabold text-white text-balance">Ít thao tác lặp lại. Nhiều thời gian cho thiết kế.</h1><p className="mt-5 text-slate-400 leading-relaxed">Năm nhóm công cụ cốt lõi giúp chuẩn hóa quy trình Revit từ dữ liệu mô hình đến bộ hồ sơ phát hành.</p></header><div className="border-t border-[var(--line)]">{features.map((feature,index) => <section key={feature.id} className="border-b border-[var(--line)]"><div className="page-shell py-12 lg:py-16 grid lg:grid-cols-2 gap-9 lg:gap-14 items-center"><div className={index%2 ? 'lg:order-2' : ''}><p className="font-mono text-xs text-slate-500 tracking-wide">{String(index+1).padStart(2,'0')} · {feature.category}</p><h2 className="mt-3 text-3xl font-bold text-white">{feature.title}</h2><p className="mt-4 text-slate-300 leading-relaxed">{feature.description}</p><ul className="mt-5 grid gap-2">{feature.bullets.map(x=><li key={x} className="flex gap-2 text-sm text-slate-300"><Check size={17} className="text-cyan-300 shrink-0"/>{x}</li>)}</ul><Link to="/download" className="mt-6 inline-flex min-h-11 items-center gap-2 font-bold text-cyan-300">Dùng thử tính năng <ArrowRight size={17}/></Link></div><figure className={index%2 ? 'lg:order-1' : ''}><div className="product-frame"><img src={feature.image} width="1280" height="960" loading={index===0?'eager':'lazy'} alt={`Mockup tính năng ${feature.title} của BIMAutomation`} /></div><figcaption className="illustration-note">Hình minh họa giao diện BIMAutomation</figcaption></figure></div></section>)}</div></div>;
}
