import React, { useRef, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Loader2 } from 'lucide-react';
import { useAuthStore } from '../../store/useAuthStore';
import { destinationAfterAuth, peekPendingIntent } from '../../utils/pendingIntent';

export default function LoginPage(){
  const [values,setValues]=useState({email:'',password:''}); const [errors,setErrors]=useState({}); const refs={email:useRef(),password:useRef()};
  const {login,loginWithGoogle,isLoading,error}=useAuthStore(); const navigate=useNavigate(); const intent=peekPendingIntent();
  const submit=async(e)=>{e.preventDefault();const next={};if(!/^\S+@\S+\.\S+$/.test(values.email))next.email='Vui lòng nhập địa chỉ email hợp lệ.';if(!values.password)next.password='Vui lòng nhập mật khẩu.';setErrors(next);const first=Object.keys(next)[0];if(first)return refs[first].current?.focus();const res=await login(values.email,values.password);if(res.success)navigate(destinationAfterAuth(),{replace:true})};
  const field=(id,label,type='text')=><div><label htmlFor={`login-${id}`} className="block text-sm font-semibold text-slate-300 mb-2">{label}</label><input ref={refs[id]} id={`login-${id}`} type={type} value={values[id]} onChange={e=>setValues({...values,[id]:e.target.value})} aria-invalid={!!errors[id]} aria-describedby={errors[id]?`login-${id}-error`:undefined} className="form-control" autoComplete={id==='password'?'current-password':'email'}/>{errors[id]&&<p id={`login-${id}-error`} className="field-error">{errors[id]}</p>}</div>;
  return <div className="page-shell min-h-[70vh] py-14 grid place-items-center"><div className="w-full max-w-md panel p-7"><h1 className="text-3xl font-bold text-white">Đăng nhập</h1><p className="mt-2 text-sm text-slate-400">{intent?.type==='checkout'?'Đăng nhập để tiếp tục với gói đã chọn.':intent?.type==='download'?'Đăng nhập để tải bản cài BIMAutomation.':'Quản lý License và đơn hàng của bạn.'}</p>{error&&<p role="alert" className="mt-4 text-sm text-rose-300">{error}</p>}<button onClick={loginWithGoogle} disabled={isLoading} className="secondary-button w-full mt-6">Tiếp tục với Google</button><div className="flex items-center gap-3 my-5 text-xs text-slate-500"><span className="h-px bg-[var(--line)] flex-1"/>hoặc<span className="h-px bg-[var(--line)] flex-1"/></div><form noValidate onSubmit={submit} className="grid gap-4">{field('email','Email','email')}<div>{field('password','Mật khẩu','password')}<Link to="/forgot-password" className="mt-2 inline-flex text-xs text-cyan-300 min-h-0">Quên mật khẩu?</Link></div><button disabled={isLoading} className="primary-button w-full">{isLoading&&<Loader2 size={18} className="animate-spin"/>}Đăng nhập</button></form><p className="mt-6 pt-5 border-t border-[var(--line)] text-center text-sm text-slate-400">Chưa có tài khoản? <Link to="/register" className="text-cyan-300 font-bold">Đăng ký</Link></p></div></div>;
}
