import React, { useRef, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Loader2 } from 'lucide-react';
import { useAuthStore } from '../../store/useAuthStore';
import { destinationAfterAuth, peekPendingIntent } from '../../utils/pendingIntent';

export default function RegisterPage(){
  const [values,setValues]=useState({fullName:'',email:'',password:''});const [errors,setErrors]=useState({});const refs={fullName:useRef(),email:useRef(),password:useRef()};
  const {register,loginWithGoogle,isLoading,error}=useAuthStore();const navigate=useNavigate();const intent=peekPendingIntent();
  const submit=async(e)=>{e.preventDefault();const next={};if(values.fullName.trim().length<2)next.fullName='Vui lòng nhập họ và tên.';if(!/^\S+@\S+\.\S+$/.test(values.email))next.email='Vui lòng nhập địa chỉ email hợp lệ.';if(values.password.length<8)next.password='Mật khẩu phải có ít nhất 8 ký tự.';setErrors(next);const first=Object.keys(next)[0];if(first)return refs[first].current?.focus();const res=await register(values.email,values.password,values.fullName);if(res.success)navigate(destinationAfterAuth(),{replace:true})};
  const field=(id,label,type='text',autocomplete)=><div><label htmlFor={`register-${id}`} className="block text-sm font-semibold text-slate-300 mb-2">{label}</label><input ref={refs[id]} id={`register-${id}`} type={type} value={values[id]} onChange={e=>setValues({...values,[id]:e.target.value})} aria-invalid={!!errors[id]} aria-describedby={errors[id]?`register-${id}-error`:undefined} className="form-control" autoComplete={autocomplete}/>{errors[id]&&<p id={`register-${id}-error`} className="field-error">{errors[id]}</p>}</div>;
  return <div className="page-shell min-h-[70vh] py-14 grid place-items-center"><div className="w-full max-w-md panel p-7"><h1 className="text-3xl font-bold text-white">Tạo tài khoản</h1><p className="mt-2 text-sm text-slate-400">{intent?.type==='checkout'?'Gói đã chọn sẽ được giữ lại sau khi đăng ký.':'Đăng ký để tải Add-in và quản lý License.'}</p>{error&&<p role="alert" className="mt-4 text-sm text-rose-300">{error}</p>}<button onClick={loginWithGoogle} disabled={isLoading} className="secondary-button w-full mt-6">Tiếp tục với Google</button><div className="flex items-center gap-3 my-5 text-xs text-slate-500"><span className="h-px bg-[var(--line)] flex-1"/>hoặc<span className="h-px bg-[var(--line)] flex-1"/></div><form noValidate onSubmit={submit} className="grid gap-4">{field('fullName','Họ và tên','text','name')}{field('email','Email','email','email')}{field('password','Mật khẩu','password','new-password')}<button disabled={isLoading} className="primary-button w-full">{isLoading&&<Loader2 size={18} className="animate-spin"/>}Tạo tài khoản</button></form><p className="mt-6 pt-5 border-t border-[var(--line)] text-center text-sm text-slate-400">Đã có tài khoản? <Link to="/login" className="text-cyan-300 font-bold">Đăng nhập</Link></p></div></div>;
}
